// examples/vue/src/App.vue
<template>
  <main class="page">
    <section>
      <h1>Partial prebundle demo (Vue)</h1>
      <p class="muted">
        下方两个组件作为入口预打包，改动后仅重建命中的入口并通过 HMR 更新。
      </p>
    </section>
    <section class="grid">
      <RegistrationForm />
      <FeedbackForm />
    </section>
  </main>
</template>

<script setup lang="ts">
import FeedbackForm from './components/FeedbackForm.vue';
import RegistrationForm from './components/RegistrationForm.vue';
</script>

<style scoped>
.page {
  max-width: 960px;
  margin: 0 auto;
  padding: 2rem;
  font-family: 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI',
    sans-serif;
}

h1 {
  margin: 0 0 0.75rem 0;
}

.muted {
  color: #5f6a86;
  margin: 0 0 1.75rem 0;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 1.25rem;
}
</style>

// examples/react/src/App.tsx
import ContactForm from './components/ContactForm';
import SignupForm from './components/SignupForm';
import LoadingResources from './components/LoadingResources';
import HeroBanner from './components/HeroBanner';
import ProfileCard from './components/ProfileCard';
import SearchBar from './components/SearchBar';
import StepsTimeline from './components/StepsTimeline';
import TagInput from './components/TagInput';
import UploadCard from './components/UploadCard';
import StatsPanel from './components/StatsPanel';

export default function App() {
  return (
    <div style={{ maxWidth: 1100, margin: '0 auto', padding: '2rem', fontFamily: 'Inter, system-ui, sans-serif', display: 'grid', gap: '1.5rem' }}>
      <HeroBanner />
      <SearchBar />
      <StatsPanel from="App Component" />
      <div style={{ display: 'grid', gap: '1rem', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))' }}>
        <SignupForm />
        <ContactForm />
        <ProfileCard />
        <LoadingResources />
        {/* 这3个组件没有调用，但还是需要预打包 */}
        {/* <TagInput />
        <UploadCard />
        <StepsTimeline /> */}
      </div>
    </div>
  );
}
